version: '3'
services:
  firebase:
    build: ./docker/node
    image: firebase_image
    container_name: firebase_container
    tty: true
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    volumes:
      - .:/app
    ports:
      - "9005:9005"
      - "5000:5000"
